---
- hosts: all
  connection: chroot
  tasks:
    - name: find netplan files ubuntu
      find:
        paths: /etc/netplan
        patterns: "*"
      register: files_to_delete
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: delete netplan files ubuntu
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: delete interface files ubuntu
      file:
        path: /etc/network/interfaces
        state: absent
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: insert interface file if ubuntu is 16.04
      copy:
        src: etc/network/interfaces
        dest: /etc/network/interfaces
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"

    - name: insert interface file if ubuntu is older than 16.04
      copy:
        src: etc/network/interfaces.old
        dest: /etc/network/interfaces
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('14.04', '<=')

    - name: check if /etc/resolv.conf exists in chroot
      stat:
        path: /etc/resolv.conf
      register: stat_result

    - name: remove immutable from /etc/resolv.conf
      file:
        path: /etc/resolv.conf
        attributes: '-i'
      when: stat_result.stat.exists and stat_result.stat.islnk == False

    - name: move /etc/resolv.conf temporarily
      command:
        cmd: mv /etc/resolv.conf /etc/resolv.conf.bak
      when: stat_result.stat.exists

    - name: create /etc/resolv.conf
      copy:
        src: resolv.conf
        dest: /etc/resolv.conf

    - name: update /etc/apt/sources.list to old. if 10.04
      copy:
        src: apt/sources.list.10.04
        dest: /etc/apt/sources.list
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "10.04"

    - name: update /etc/apt/sources.list to old. if 12.04
      copy:
        src: apt/sources.list.12.04
        dest: /etc/apt/sources.list
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "12.04"

    - name: update /etc/apt/sources.list to old. if 14.04
      copy:
        src: apt/sources.list.14.04
        dest: /etc/apt/sources.list
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "14.04"

    - name: update /etc/apt/sources.list to old. if 16.04
      copy:
        src: apt/sources.list.16.04
        dest: /etc/apt/sources.list
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"

    - name: update /etc/apt/sources.list to old. if 18.04
      copy:
        src: apt/sources.list.18.04
        dest: /etc/apt/sources.list
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "18.04"

    - name: update /etc/apt/sources.list to old. if debian 9
      copy:
        src: apt/sources.list.debian.9
        dest: /etc/apt/sources.list
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == "9"

    - name: update repo if ubuntu
      shell: apt-get -o Dir::Etc::SourceParts=/etc/apt/sources.list update
      ignore_errors: true
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: fix broken installs if present
      shell: apt-get --fix-broken install -y
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: update cloud-init if ubuntu
      apt:
        name: cloud-init
        state: latest
        force: yes
        update_cache: no
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: update CentOS-Base.repo to vault if CentOS7.6
      copy:
        src: yum/CentOS-Base.repo7.6
        dest: /etc/yum.repos.d/CentOS-Base.repo
      when: ansible_distribution == 'CentOS' and ansible_distribution_version == "7.6"

    - name: update cloud-init if centos
      yum:
        name: cloud-init
        state: latest
        update_cache: yes
      when: ansible_distribution == 'CentOS'

    - name: run cloud-init clean
      shell: cloud-init clean
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('16.04', '>')

    - name: run cloud-init clean CentOS
      shell: cloud-init clean
      when: ansible_distribution == 'CentOS'

    - name: preserve hostname
      replace:
        path: /etc/cloud/cloud.cfg
        regexp: "^preserve_hostname: false$"
        replace: "preserve_hostname: true"

    - name: reset resolv.conf
      command:
        cmd: mv /etc/resolv.conf.bak /etc/resolv.conf
      when: stat_result.stat.exists
