#!/bin/bash

transferlog="/var/log/vm-transfer.log"
chrootlog="/var/log/vm-chroot.log"

check_process() {
    local process_name="$1"
    ps aux | grep "[${process_name:0:1}]${process_name:1}" | wc -l
}

check_success() {
    local log_file="$1"
    local success_message="volume update completed successfully"
    if [ -f "$log_file" ] && [ -s "$log_file" ]; then
        grep -c "$success_message" "$log_file"
    else
        echo 0
    fi
}

time_difference() {
    local log_file="$1"
    if [ -f "$log_file" ]; then
        local current_time=$(date +%s)
        local last_modification=$(stat -c %Y "$log_file")
        echo $(( (current_time - last_modification) / 60 ))
    else
        echo 999999
    fi
}

transfer_process=$(check_process "vm-transfer")
chroot_process=$(check_process "vm-chroot")
success=$(check_success "$chrootlog")
difference_transferlog=$(time_difference "$transferlog")
difference_chrootlog=$(time_difference "$chrootlog")

if [ $difference_transferlog -lt 600 ] && [ $transfer_process -gt 0 ]; then
    echo "INFO : Active transfer job running"
    exit 69
elif [ $difference_chrootlog -lt 600 ] && [ $chroot_process -gt 0 ]; then
    echo "INFO : Active chroot job running"
    exit 69
elif [ $transfer_process -eq 0 ] && [ $chroot_process -eq 0 ] && [ "$success" -gt 0 ]; then
    echo "INFO : Job completed successfully"
    exit 0
else
    echo "INFO : No active jobs"
    exit 1
fi
