#!/bin/bash

set -o pipefail

LOG_FILE="/var/log/vm-transfer.log"
> "$LOG_FILE"

transfer_data() {
    local hypervisor="$1"
    local spath="$2"
    local tpath="$3"
    local sshkey="$4"

    local sshlocal=$(which ssh)
    local ddlocal=$(which dd)
    local ddremote=$(ssh -i "$sshkey" root@"$hypervisor" which dd)

    $sshlocal -i "$sshkey" root@"$hypervisor" \
        "$ddremote" if="$spath" bs=4M status=progress | \
        "$ddlocal" of="$tpath" bs=4M status=progress > "$LOG_FILE" 2>&1

    local exit_status=$?

    if [ $exit_status -eq 0 ]; then
        echo "$(date '+%Y-%m-%d %H:%M:%S') - Transfer successful." >> "$LOG_FILE"
    else
        echo "$(date '+%Y-%m-%d %H:%M:%S') - Transfer failed with exit status $exit_status." >> "$LOG_FILE"
    fi
}

hypervisor=""
spath=""
tpath="/dev/vdb"
sshkey=""

options="Available options:
  --hypervisor | -H : Specify the hypervisor address.
  --spath      | -S : Specify the source path for the data to be transferred.
  --tpath      | -T : Specify the target path where the data will be transferred.
  --sshkey     | -K : Specify the SSH key path for authentication."

while [[ $# -gt 0 ]]; do
    case "$1" in
        --hypervisor | -H)
            shift
            hypervisor="$1"
            ;;
        --spath | -S)
            shift
            spath="$1"
            ;;
        --tpath | -T)
            shift
            tpath="$1"
            ;;
        --sshkey | -K)
            shift
            sshkey="$1"
            ;;
        *)
            echo "Unknown option: $1"
	    echo "$options"
            exit 1
            ;;
    esac
    shift
done

if [[ "$tpath" == "/dev/vdb" ]] && [ ! -e "/dev/vdb" ]; then
    echo "Target path is not specified and default path $tpath does not exist. Aborting."
    exit 1
fi

if [[ -z "$hypervisor" ]]; then
    echo "Please provide hypervisor using --hypervisor or -H."
    exit 1
fi

if [[ -z "$spath" ]]; then
    echo "Please provide source path using --spath or -S."
    exit 1
fi

if [[ -z "$sshkey" ]] || [ ! -f "$sshkey" ]; then
    echo "SSH key path is not specified or does not exist. Please provide a valid sshkey using --sshkey or -K."
    exit 1
fi

transfer_data "$hypervisor" "$spath" "$tpath" "$sshkey"
